version: "3"

services:
  database:
    image: postgres:latest
    hostname: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    env_file: ./.env
    volumes:
      - /var/lib/postgresql/data/
    restart: unless-stopped

  darkstore-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: darkstore-api
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_PROFILES_ACTIVE: docker
    restart: unless-stopped