spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/darkstore
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    hidden-method:
      filter:
        enabled: true

rate-limiter:
  capacity: 30
  refillTokens: 10
  refillDurationInSeconds: 10
  initialTokens: 30

security:
  jwt:
    secret-key: 8010b14e15f274416898ad78da0539940ba32fb19e6d40bed348c94f678c8e01
    expiration-in-ms: 86400000
