spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/darkstore
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    hidden-method:
      filter:
        enabled: true

rate-limiter:
  capacity: 10
  refillTokens: 10
  refillDurationInSeconds: 10
  initialTokens: 10
